import { defineConfig } from "oxlint";
import core from "ultracite/oxlint/core";

const off = (rules: string[]) =>
  Object.fromEntries(rules.map((rule) => [rule, "off" as const]));

export default defineConfig({
  extends: [core],
  // Use the preset's explicit rules, not extra category defaults from new plugins.
  categories: { correctness: "off" },
  plugins: [...core.plugins, "react"],
  env: { node: true, bun: true },
  // Lint every TypeScript source, but not vendored JavaScript or documentation.
  ignorePatterns: [
    "**/*",
    "!**/",
    "!**/*.ts",
    "node_modules/",
    ".pi/",
    "skills/composition-patterns/",
  ],
  overrides: [
    {
      files: ["**/*.{test,spec}.ts", "setup.test.ts"],
      rules: { "typescript/no-explicit-any": "off" },
    },
  ],
  rules: {
    // Declaration, ordering and comment styles not enforced under prior Biome config.
    ...off([
      "block-scoped-var",
      "class-methods-use-this",
      "complexity",
      "func-name-matching",
      "func-names",
      "func-style",
      "id-match",
      "max-classes-per-file",
      "max-nested-callbacks",
      "no-caller",
      "no-delete-var",
      "no-div-regex",
      "no-eq-null",
      "no-extend-native",
      "no-extra-bind",
      "no-implicit-globals",
      "no-inline-comments",
      "no-iterator",
      "no-loop-func",
      "no-multi-assign",
      "no-multi-str",
      "no-new",
      "no-new-func",
      "no-plusplus",
      "no-promise-executor-return",
      "no-proto",
      "no-script-url",
      "no-unexpected-multiline",
      "no-unmodified-loop-condition",
      "no-useless-call",
      "no-useless-return",
      "no-warning-comments",
      "prefer-destructuring",
      "prefer-object-has-own",
      "prefer-promise-reject-errors",
      "prefer-rest-params",
      "prefer-spread",
      "preserve-caught-error",
      "require-unicode-regexp",
      "sort-keys",
      "sort-vars",
      "unicode-bom",
      "vars-on-top",
    ]),
    // These stricter variants were not enforced under prior Biome config:
    // array-type rejects complex T[] that useConsistentArrayType accepts;
    // require-await rejects async callbacks returning values; no-invalid-void-type
    // rejects void unions in callback return types that noConfusingVoidType accepts.
    // no-use-before-define also rejects valid deferred class/variable references;
    // no-redeclare rejects valid TypeScript value/type declarations sharing a name.
    ...off([
      "typescript/array-type",
      "require-await",
      "typescript/no-invalid-void-type",
      "no-use-before-define",
      "no-redeclare",
    ]),
    // Import resolution and JSDoc conventions not enforced under prior Biome config.
    ...off([
      "import/consistent-type-specifier-style",
      "import/default",
      "import/first",
      "import/namespace",
      "import/newline-after-import",
      "import/no-absolute-path",
      "import/no-amd",
      "import/no-cycle",
      "import/no-duplicates",
      "import/no-empty-named-blocks",
      "import/no-mutable-exports",
      "import/no-named-as-default",
      "import/no-named-as-default-member",
      "import/no-named-default",
      "import/no-self-import",
      "import/no-webpack-loader-syntax",
      "jsdoc/check-access",
      "jsdoc/check-property-names",
      "jsdoc/check-tag-names",
      "jsdoc/empty-tags",
      "jsdoc/implements-on-classes",
      "jsdoc/no-defaults",
      "jsdoc/require-param-description",
      "jsdoc/require-param-name",
      "jsdoc/require-property",
      "jsdoc/require-property-description",
      "jsdoc/require-property-name",
      "jsdoc/require-property-type",
      "jsdoc/require-returns-description",
      "jsdoc/require-throws-description",
      "jsdoc/require-throws-type",
      "jsdoc/require-yields",
      "jsdoc/require-yields-type",
      "node/global-require",
      "node/handle-callback-err",
      "node/no-exports-assign",
      "node/no-new-require",
      "node/no-path-concat",
    ]),
    // Oxc-only checks and promise style not enforced under prior Biome config.
    ...off([
      "oxc/bad-array-method-on-arguments",
      "oxc/bad-bitwise-operator",
      "oxc/bad-char-at-comparison",
      "oxc/bad-comparison-sequence",
      "oxc/bad-object-literal-comparison",
      "oxc/bad-replace-all-arg",
      "oxc/const-comparisons",
      "oxc/double-comparisons",
      "oxc/erasing-op",
      "oxc/missing-throw",
      "oxc/no-async-endpoint-handlers",
      "oxc/no-this-in-exported-function",
      "oxc/number-arg-out-of-range",
      "oxc/only-used-in-recursion",
      "oxc/uninvoked-array-callback",
      "promise/avoid-new",
      "promise/no-callback-in-promise",
      "promise/no-multiple-resolved",
      "promise/no-nesting",
      "promise/no-new-statics",
      "promise/no-promise-in-callback",
      "promise/no-return-wrap",
      "promise/param-names",
      "promise/prefer-await-to-callbacks",
      "promise/prefer-await-to-then",
      "promise/prefer-catch",
      "promise/spec-only",
      "promise/valid-params",
    ]),
    // Extra TypeScript/type-aware restrictions not enforced under prior Biome config.
    // Bug-catching type-aware rules are enabled explicitly below.
    ...off([
      "typescript/ban-tslint-comment",
      "typescript/class-literal-property-style",
      "typescript/consistent-generic-constructors",
      "typescript/consistent-indexed-object-style",
      "typescript/consistent-return",
      "typescript/consistent-type-assertions",
      "typescript/dot-notation",
      "typescript/no-array-delete",
      "typescript/no-confusing-non-null-assertion",
      "typescript/no-confusing-void-expression",
      "typescript/no-deprecated",
      "typescript/no-duplicate-enum-values",
      "typescript/no-duplicate-type-constituents",
      "typescript/no-dynamic-delete",
      "typescript/no-empty-object-type",
      "typescript/no-extraneous-class",
      "typescript/no-for-in-array",
      "typescript/no-meaningless-void-operator",
      "typescript/no-mixed-enums",
      "typescript/no-non-null-asserted-nullish-coalescing",
      "typescript/no-redundant-type-constituents",
      "typescript/no-unnecessary-boolean-literal-compare",
      "typescript/no-unnecessary-parameter-property-assignment",
      "typescript/no-unnecessary-template-expression",
      "typescript/no-unnecessary-type-arguments",
      "typescript/no-unnecessary-type-assertion",
      "typescript/no-unnecessary-type-conversion",
      "typescript/no-unnecessary-qualifier",
      "typescript/no-unnecessary-type-parameters",
      "typescript/no-unsafe-argument",
      "typescript/no-unsafe-assignment",
      "typescript/no-unsafe-call",
      "typescript/no-unsafe-enum-comparison",
      "typescript/no-unsafe-function-type",
      "typescript/no-unsafe-member-access",
      "typescript/no-unsafe-return",
      "typescript/no-unsafe-type-assertion",
      "typescript/no-unsafe-unary-minus",
      "typescript/no-useless-default-assignment",
      "typescript/non-nullable-type-assertion-style",
      "typescript/prefer-find",
      "typescript/prefer-includes",
      "typescript/prefer-nullish-coalescing",
      "typescript/prefer-reduce-type-parameter",
      "typescript/prefer-regexp-exec",
      "typescript/prefer-return-this-type",
      "typescript/prefer-string-starts-ends-with",
      "typescript/promise-function-async",
      "typescript/related-getter-setter-pairs",
      "typescript/restrict-plus-operands",
      "typescript/strict-boolean-expressions",
      "typescript/strict-void-return",
      "typescript/triple-slash-reference",
    ]),
    // Extra Unicorn idioms not enforced under prior Biome config.
    ...off([
      "unicorn/consistent-template-literal-escape",
      "unicorn/catch-error-name",
      "unicorn/consistent-date-clone",
      "unicorn/consistent-empty-array-spread",
      "unicorn/consistent-existence-index-check",
      "unicorn/consistent-function-scoping",
      "unicorn/custom-error-definition",
      "unicorn/empty-brace-spaces",
      "unicorn/escape-case",
      "unicorn/no-abusive-eslint-disable",
      "unicorn/no-accessor-recursion",
      "unicorn/no-anonymous-default-export",
      "unicorn/no-array-method-this-argument",
      "unicorn/no-array-reduce",
      "unicorn/no-array-reverse",
      "unicorn/no-array-sort",
      "unicorn/no-await-expression-member",
      "unicorn/no-await-in-promise-methods",
      "unicorn/no-console-spaces",
      "unicorn/no-empty-file",
      "unicorn/no-hex-escape",
      "unicorn/no-immediate-mutation",
      "unicorn/no-instanceof-builtins",
      "unicorn/no-invalid-fetch-options",
      "unicorn/no-invalid-remove-event-listener",
      "unicorn/no-length-as-slice-end",
      "unicorn/no-magic-array-flat-depth",
      "unicorn/no-negation-in-equality-check",
      "unicorn/no-new-buffer",
      "unicorn/no-object-as-default-parameter",
      "unicorn/no-single-promise-in-promise-methods",
      "unicorn/no-typeof-undefined",
      "unicorn/no-unnecessary-array-flat-depth",
      "unicorn/no-unnecessary-array-splice-count",
      "unicorn/no-unnecessary-await",
      "unicorn/no-unnecessary-slice-end",
      "unicorn/no-unreadable-array-destructuring",
      "unicorn/no-unreadable-iife",
      "unicorn/no-useless-collection-argument",
      "unicorn/no-useless-error-capture-stack-trace",
      "unicorn/no-useless-fallback-in-spread",
      "unicorn/no-useless-length-check",
      "unicorn/no-useless-promise-resolve-reject",
      "unicorn/no-useless-spread",
      "unicorn/no-zero-fractions",
      "unicorn/prefer-add-event-listener",
      "unicorn/prefer-array-find",
      "unicorn/prefer-array-flat",
      "unicorn/prefer-array-some",
      "unicorn/prefer-bigint-literals",
      "unicorn/prefer-blob-reading-methods",
      "unicorn/prefer-class-fields",
      "unicorn/prefer-classlist-toggle",
      "unicorn/prefer-code-point",
      "unicorn/prefer-default-parameters",
      "unicorn/prefer-dom-node-append",
      "unicorn/prefer-dom-node-dataset",
      "unicorn/prefer-dom-node-remove",
      "unicorn/prefer-dom-node-text-content",
      "unicorn/prefer-event-target",
      "unicorn/prefer-import-meta-properties",
      "unicorn/prefer-includes",
      "unicorn/prefer-keyboard-event-key",
      "unicorn/prefer-logical-operator-over-ternary",
      "unicorn/prefer-math-min-max",
      "unicorn/prefer-math-trunc",
      "unicorn/prefer-modern-dom-apis",
      "unicorn/prefer-modern-math-apis",
      "unicorn/prefer-module",
      "unicorn/prefer-native-coercion-functions",
      "unicorn/prefer-negative-index",
      "unicorn/prefer-object-from-entries",
      "unicorn/prefer-prototype-methods",
      "unicorn/prefer-query-selector",
      "unicorn/prefer-reflect-apply",
      "unicorn/prefer-regexp-test",
      "unicorn/prefer-set-has",
      "unicorn/prefer-set-size",
      "unicorn/prefer-spread",
      "unicorn/prefer-string-replace-all",
      "unicorn/prefer-string-slice",
      "unicorn/prefer-string-starts-ends-with",
      "unicorn/prefer-structured-clone",
      "unicorn/prefer-ternary",
      "unicorn/prefer-type-error",
      "unicorn/relative-url-style",
      "unicorn/require-array-join-separator",
      "unicorn/require-module-attributes",
      "unicorn/require-module-specifiers",
      "unicorn/require-post-message-target-origin",
      "unicorn/switch-case-braces",
      "unicorn/switch-case-break-position",
      "unicorn/text-encoding-identifier-case",
    ]),
    // Explicit local policy carried over from the previous configuration.
    curly: "error",
    "getter-return": "error",
    "no-unreachable": "error",
    "react/exhaustive-deps": "off",
    "no-shadow": "warn",
    "typescript/no-non-null-assertion": "off",
    "typescript/consistent-type-definitions": ["error", "interface"],
    "unicorn/no-useless-undefined": [
      "error",
      { checkArguments: false, checkArrowFunctionBody: false },
    ],
    "one-var": ["error", "never"],
    "react/self-closing-comp": "error",
    "react/jsx-no-useless-fragment": "error",
    "no-unused-vars": [
      "error",
      {
        vars: "all",
        args: "all",
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
      },
    ],
    "no-param-reassign": "error",
    "default-param-last": "error",
    eqeqeq: ["error", "always", { null: "ignore" }],
    "no-else-return": ["error", { allowElseIf: false }],
    "typescript/no-inferrable-types": "error",
    "no-console": "off",
    "no-magic-numbers": "off",
    "default-case": "off",
    "oxc/no-barrel-file": "off",
    "import/no-namespace": "off",
    // Bug-catching type-aware rules; style-level type-aware rules stay off above.
    "typescript/await-thenable": "error",
    "typescript/no-base-to-string": "error",
    "typescript/no-floating-promises": "error",
    "typescript/no-misused-promises": "error",
    "typescript/no-misused-spread": "error",
    "typescript/prefer-promise-reject-errors": "error",
    "typescript/require-array-sort-compare": "error",
    "typescript/restrict-template-expressions": "error",
    "typescript/return-await": "error",
    "typescript/switch-exhaustiveness-check": "error",
    "typescript/unbound-method": "error",
    "typescript/use-unknown-in-catch-callback-variable": "error",
  },
});
