// Representative installed shapes recorded in the execution brief:
// pi-tasks 0.9.0, pi-mcp-adapter 5.0.0, Pi codemode 1.0.2,
// pi-web-access 0.30.0. No external package imports are needed for drawing.
export const companionFixtures = [
  {
    name: "TaskCreate",
    group: "tasks",
    args: { subject: "Fix renderer", description: "Draw tools" },
    details: undefined,
    text: "Created task #1",
    call: "Fix renderer",
    summary: "Created task #1",
  },
  {
    name: "TaskList",
    group: "tasks",
    args: {},
    details: undefined,
    text: "1 task",
    call: "all tasks",
    summary: "1 task",
  },
  {
    name: "TaskGet",
    group: "tasks",
    args: { taskId: "1" },
    details: undefined,
    text: "#1 Fix renderer",
    call: "#1",
    summary: "#1 Fix renderer",
  },
  {
    name: "TaskUpdate",
    group: "tasks",
    args: { taskId: "1", status: "in_progress" },
    details: undefined,
    text: "Updated task #1",
    call: "#1 · in_progress",
    summary: "Updated task #1",
  },
  {
    name: "TaskOutput",
    group: "tasks",
    args: { task_id: "1", block: true, timeout: 1000 },
    details: undefined,
    text: "Task output",
    call: "#1",
    summary: "Task output",
  },
  {
    name: "TaskStop",
    group: "tasks",
    args: { shell_id: "sh1" },
    details: undefined,
    text: "Stopped shell",
    call: "shell sh1",
    summary: "Stopped shell",
  },
  {
    name: "TaskExecute",
    group: "tasks",
    args: { task_ids: ["1", "2"], additional_context: "Check drawing" },
    details: undefined,
    text: "Executing 2 tasks",
    call: "2 tasks",
    summary: "Executing 2 tasks",
  },
  {
    name: "mcp",
    group: "mcp",
    args: { tool: "lookup", server: "docs", args: { query: "Pi" } },
    details: { server: "docs", tool: "lookup", mcpResult: { content: [] } },
    text: "Found docs",
    call: "docs · lookup",
    summary: "Found docs",
  },
  {
    name: "mcp__docs",
    group: "mcp",
    args: { tool: "lookup", args: '{"query":"Pi"}' },
    details: { server: "docs", tool: "lookup", outputGuard: {} },
    text: "Found docs",
    call: "docs · lookup",
    summary: "Found docs",
  },
  {
    name: "mcp__docs__prompt",
    group: "mcp",
    args: { tool: "prompt" },
    details: {
      mode: "error",
      error: "Unavailable",
      server: "docs",
      requestedTool: "prompt",
    },
    text: "Unavailable",
    call: "docs · prompt",
    summary: "Unavailable",
  },
  {
    name: "mcp",
    group: "mcp",
    args: { search: "docs" },
    details: {
      mode: "search",
      matches: [{ server: "docs", tool: "lookup", score: 1 }],
      count: 3,
      hasMore: false,
      nextOffset: null,
      query: "docs",
    },
    text: "Found tools",
    call: "search · docs",
    summary: "3 tools",
  },
  {
    name: "mcp",
    group: "mcp",
    args: { connect: "docs" },
    details: {
      mode: "list",
      server: "docs",
      tools: ["lookup"],
      count: 1,
      hasInstructions: true,
    },
    text: "Connected",
    call: "connect · docs",
    summary: "1 tool · docs",
  },
  {
    name: "mcp",
    group: "mcp",
    args: { instructions: "docs" },
    details: { mode: "instructions", server: "docs", length: 42 },
    text: "Usage instructions",
    call: "instructions · docs",
    summary: "Usage instructions",
  },
  {
    name: "mcp",
    group: "mcp",
    args: { describe: "docs_lookup" },
    details: {
      mode: "describe",
      server: "docs",
      tool: {
        name: "lookup",
        description: "Lookup docs",
        inputSchema: { type: "object" },
      },
    },
    text: "Tool schema",
    call: "describe · docs_lookup",
    summary: "Tool schema",
  },
  {
    name: "mcp",
    group: "mcp",
    args: { action: "auth-start", server: "docs" },
    details: { mode: "auth-start", server: "docs", authenticated: true },
    text: "Authenticated",
    call: "auth-start · docs",
    summary: "Authenticated",
  },
  {
    name: "codemode",
    group: "codemode",
    args: {
      code: '\nconst x = await tools.read({path: "a"});\n\nconsole.log(x);',
    },
    details: {
      calls: [
        {
          id: "nested-1",
          name: "read",
          args: '{"path":"a"}',
          status: "ok",
          durationMs: 10,
        },
      ],
      fullOutputPath: "/tmp/output",
    },
    text: "Script completed\noutput",
    call: "codemode → running",
    summary: "1 tool call · 23 bytes",
  },
  {
    name: "web_search",
    group: "web",
    args: { queries: ["Pi tools", "Pi themes"] },
    details: {
      queries: ["Pi tools", "Pi themes"],
      queryCount: 2,
      successfulQueries: 2,
      totalResults: 5,
      searchId: "r1",
      includeContent: false,
    },
    text: "Search results",
    call: "2 queries · Pi tools",
    summary: "5 results · 2/2 queries",
  },
  {
    name: "source_check",
    group: "web",
    args: { claim: "Pi supports renderers" },
    details: { responseId: "r1", sourceCount: 3, passageCount: 5 },
    text: "Sources checked",
    call: "Pi supports renderers",
    summary: "3 sources · 5 passages",
  },
  {
    name: "fetch_content",
    group: "web",
    args: { urls: ["https://example.com", "https://example.org"] },
    details: {
      urls: ["https://example.com", "https://example.org"],
      urlCount: 2,
      successful: 1,
      totalChars: 100,
    },
    text: "Page content",
    call: "2 URLs · https://example.com",
    summary: "1/2 URLs · 100 chars",
  },
  {
    name: "get_search_content",
    group: "web",
    args: { responseId: "r1", queryIndex: 0, urlIndex: 1 },
    details: { error: "Not found" },
    text: "Not found",
    call: "r1 · query #0 · URL #1",
    summary: "Not found",
  },
] as const;
