import { expect, test } from "bun:test";

import { parseFrontmatter } from "@earendil-works/pi-coding-agent";

import { generateAgent, parseRepoAgent, resolveAgent } from "./agents";

const GENERATED_COMMENT = /# generated by supa-pi model-profiles[^\n]*\n/;
const content =
  "---\nname: worker\ndescription: keep me\nmodel: p/base\nthinking: low\ntools: read\n---\n\nBody exactly.\n";

test("named > wildcard > repo independently per field; frontmatter name is the key", () => {
  const agent = parseRepoAgent("/repo/agents/file.md", content);
  expect(agent.name).toBe("worker");
  expect(
    resolveAgent(agent, {
      agents: {
        "*": { model: "p/wild", thinking: "medium" },
        worker: { thinking: "high" },
      },
    }),
  ).toEqual({ model: "p/wild", thinking: "high" });
  expect(resolveAgent(agent, {})).toEqual({ model: "p/base", thinking: "low" });
  expect(parseRepoAgent("/repo/agents/file.md", "Body").name).toBe("file");
});

test("generated frontmatter comment is tolerated by Pi; body and unrelated fields unchanged", () => {
  const agent = parseRepoAgent("/repo/agents/file.md", content);
  const generated = generateAgent(agent, { model: "p/new", thinking: "max" });
  expect(generated.replace(GENERATED_COMMENT, "")).toBe(
    content
      .replace("p/base", "p/new")
      .replace("thinking: low", "thinking: max"),
  );
  expect(parseFrontmatter(generated).frontmatter).toMatchObject({
    name: "worker",
    model: "p/new",
    thinking: "max",
    tools: "read",
  });
});

test("inserts absent fields and marker without disturbing empty frontmatter or CRLF body", () => {
  for (const contentWithFence of [
    "---\n---\nBody\n",
    "\uFEFF---\r\nname: worker\r\n---\r\n\r\nBody\r\n",
  ]) {
    const agent = parseRepoAgent("/repo/agents/file.md", contentWithFence);
    const generated = generateAgent(agent, {
      model: "p/new",
      thinking: "high",
    });
    expect(parseFrontmatter(generated).frontmatter).toMatchObject({
      model: "p/new",
      thinking: "high",
    });
    expect(generated.split("---")).toHaveLength(3);
    expect(generated.slice(generated.lastIndexOf("---") + 3)).toBe(
      contentWithFence.slice(contentWithFence.lastIndexOf("---") + 3),
    );
  }
});

test("no frontmatter: insert fields; ownership requires marker inside frontmatter", () => {
  const agent = parseRepoAgent("/repo/agents/file.md", "Exact body\n");
  const generated = generateAgent(agent, { model: "p/new", thinking: "off" });
  expect(generated.endsWith("---\nExact body\n")).toBe(true);
  expect(parseFrontmatter(generated).frontmatter).toMatchObject({
    model: "p/new",
    thinking: "off",
  });
});

test("model identifiers that need YAML quoting round-trip through Pi", () => {
  const agent = parseRepoAgent("/repo/agents/file.md", content);
  const generated = generateAgent(agent, {
    model: "p/model:",
    thinking: "max",
  });
  expect(parseFrontmatter(generated).frontmatter.model).toBe("p/model:");
});
