import { readdirSync, readFileSync } from "node:fs";
import { basename, join, resolve } from "node:path";

import { parseFrontmatter } from "@earendil-works/pi-coding-agent";

import type { Profile, Values } from "./config";

export const MARKER = "# generated by supa-pi model-profiles from ";
const FRONTMATTER =
  /^(?:\uFEFF)?---(\r\n|\n|\r)(?:([\s\S]*?)(?:\r\n|\n|\r))?---(?=\r?\n|\r|$)/;
const PLAIN_SCALAR = /^[a-zA-Z0-9_./-]+$/;
const OWNERSHIP_MARKER =
  /^# generated by supa-pi model-profiles from [^\r\n]*; do not edit$/m;

export interface RepoAgent {
  name: string;
  filename: string;
  path: string;
  content: string;
  baseline: { model?: string; thinking?: string };
}

export function parseRepoAgent(path: string, content: string): RepoAgent {
  const { frontmatter } = parseFrontmatter(content);
  // pi-subagents keys by trimmed frontmatter name, falling back to the filename.
  const declared =
    typeof frontmatter.name === "string" ? frontmatter.name.trim() : "";
  return {
    name: declared || basename(path, ".md"),
    filename: basename(path),
    path: resolve(path),
    content,
    baseline: {
      model:
        typeof frontmatter.model === "string" ? frontmatter.model : undefined,
      thinking:
        typeof frontmatter.thinking === "string"
          ? frontmatter.thinking
          : undefined,
    },
  };
}

export function readRepoAgents(dir: string): RepoAgent[] {
  const agents = readdirSync(dir)
    .filter((name) => name.endsWith(".md"))
    .sort()
    .map((name) => {
      const path = join(dir, name);
      try {
        return parseRepoAgent(path, readFileSync(path, "utf8"));
      } catch (error) {
        throw new Error(`${path}: ${String(error)}`);
      }
    });
  const names = new Set<string>();
  for (const agent of agents) {
    if (names.has(agent.name)) {
      throw new Error(`${agent.path}: duplicate agent name ${agent.name}`);
    }
    names.add(agent.name);
  }
  return agents;
}

export function resolveAgent(
  agent: RepoAgent,
  profile: Profile
): RepoAgent["baseline"] {
  const named = profile.agents?.[agent.name];
  const wildcard = profile.agents?.["*"];
  return {
    model: named?.model ?? wildcard?.model ?? agent.baseline.model,
    thinking: named?.thinking ?? wildcard?.thinking ?? agent.baseline.thinking,
  };
}

export function needsOverride(
  agent: RepoAgent,
  values: RepoAgent["baseline"]
): boolean {
  return (
    values.model !== agent.baseline.model ||
    values.thinking !== agent.baseline.thinking
  );
}

export function isGenerated(content: string): boolean {
  return OWNERSHIP_MARKER.test(content.match(FRONTMATTER)?.[2] ?? "");
}

export function generateAgent(
  agent: RepoAgent,
  values: RepoAgent["baseline"] | Values
): string {
  const match = agent.content.match(FRONTMATTER);
  const eol = match?.[1] ?? (agent.content.includes("\r\n") ? "\r\n" : "\n");
  let yaml = match?.[2] ?? "";
  for (const field of ["model", "thinking"] as const) {
    // Only changed fields are edited: preserve exact spelling/quoting of repo defaults.
    if (
      values[field] === agent.baseline[field] ||
      values[field] === undefined
    ) {
      continue;
    }
    const value = values[field];
    const scalar = PLAIN_SCALAR.test(value) ? value : JSON.stringify(value);
    const line = `${field}: ${scalar}`;
    const pattern = new RegExp(`^${field}:[^\\r\\n]*`, "m");
    yaml = pattern.test(yaml)
      ? yaml.replace(pattern, line)
      : `${yaml}${yaml ? eol : ""}${line}`;
  }
  yaml += `${yaml ? eol : ""}${MARKER}${agent.path}; do not edit`;
  if (match) {
    const opening = match[0].slice(
      0,
      match[0].startsWith("\uFEFF") ? 4 + eol.length : 3 + eol.length
    );
    return `${opening}${yaml}${eol}---${agent.content.slice(match[0].length)}`;
  }
  return `---${eol}${yaml}${eol}---${eol}${agent.content}`;
}
